#!/usr/bin/env python3

from ultralytics import YOLO

# Load a pretrained YOLOv8n model
model = YOLO('yolov8n.pt')

source1 = './robutler_bringup_tp3/person_laptop/laptop.jpg'

# Run inference on 'IMAGE1' with arguments
model.predict(source1, save=True, imgsz=320, conf=0.5, save_txt = True)


path1 = "./runs/detect/predict/labels/Person1.txt"
#with open(path1) as f:
#    c = f.read()
#    if not c:
#        has_people.append(False)
#    elif c[0] != '0':
#        has_people.append(False)
#    else:
#        has_people.append(True)
        
 